/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentesgraficos;

import java.awt.Component;
import static java.lang.System.exit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author daw-B
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        vDatos = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1DatosUsuario = new javax.swing.JPanel();
        jTextField1NombreUsuario = new javax.swing.JTextField();
        jTextField1TelefonoUsuario = new javax.swing.JTextField();
        jButton1GuardarDatosUsuario = new javax.swing.JButton();
        jSpinner1EdadUsuario = new javax.swing.JSpinner();
        jLabel1IndicarEdad = new javax.swing.JLabel();
        jButton1Salir = new javax.swing.JButton();
        jRadioButton1ActivarDatos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1AlmacenarDatos = new javax.swing.JTextArea();
        jRadioButton1ActivarAlmacenamiento = new javax.swing.JRadioButton();
        jButton1CambiarVentana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1DatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Usuario"));

        jTextField1NombreUsuario.setText("Nombre Usuario");
        jTextField1NombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1NombreUsuarioMouseClicked(evt);
            }
        });

        jTextField1TelefonoUsuario.setText("Telefono Usuario");
        jTextField1TelefonoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1TelefonoUsuarioFocusGained(evt);
            }
        });

        jButton1GuardarDatosUsuario.setText("Guardar");
        jButton1GuardarDatosUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1GuardarDatosUsuarioMouseClicked(evt);
            }
        });

        jLabel1IndicarEdad.setText("Fija abajo la edad del usuario");

        javax.swing.GroupLayout jPanel1DatosUsuarioLayout = new javax.swing.GroupLayout(jPanel1DatosUsuario);
        jPanel1DatosUsuario.setLayout(jPanel1DatosUsuarioLayout);
        jPanel1DatosUsuarioLayout.setHorizontalGroup(
            jPanel1DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1DatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1DatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel1IndicarEdad)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1DatosUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanel1DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1NombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(jTextField1TelefonoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                            .addComponent(jSpinner1EdadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jButton1GuardarDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        jPanel1DatosUsuarioLayout.setVerticalGroup(
            jPanel1DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1DatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1TelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1IndicarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1DatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1DatosUsuarioLayout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jButton1GuardarDatosUsuario))
                    .addComponent(jSpinner1EdadUsuario))
                .addGap(20, 20, 20))
        );

        jButton1Salir.setText("Pulsa para salir");
        jButton1Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1SalirMouseClicked(evt);
            }
        });

        jRadioButton1ActivarDatos.setText("Activar Datos Usuario");
        jRadioButton1ActivarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1ActivarDatosMouseClicked(evt);
            }
        });

        jTextArea1AlmacenarDatos.setColumns(20);
        jTextArea1AlmacenarDatos.setRows(5);
        jScrollPane1.setViewportView(jTextArea1AlmacenarDatos);

        jRadioButton1ActivarAlmacenamiento.setText("Activar Almacenamiento");
        jRadioButton1ActivarAlmacenamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1ActivarAlmacenamientoMouseClicked(evt);
            }
        });

        jButton1CambiarVentana.setText("Cambiar Ventana");
        jButton1CambiarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1CambiarVentanaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1DatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1ActivarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1ActivarAlmacenamiento)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1CambiarVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1Salir))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1ActivarAlmacenamiento)
                    .addComponent(jRadioButton1ActivarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1Salir)
                            .addComponent(jButton1CambiarVentana)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1DatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1SalirMouseClicked
        // Guardar
        int opc = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro que quieres seguir?");
        if (opc == JOptionPane.YES_OPTION){
            exit(0);
        }
        
    }//GEN-LAST:event_jButton1SalirMouseClicked

    private void jTextField1NombreUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1NombreUsuarioMouseClicked
        jTextField1NombreUsuario.setText("");
    }//GEN-LAST:event_jTextField1NombreUsuarioMouseClicked

    private void jTextField1TelefonoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1TelefonoUsuarioFocusGained
        jTextField1TelefonoUsuario.setText("");
    }//GEN-LAST:event_jTextField1TelefonoUsuarioFocusGained

    private void jButton1GuardarDatosUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1GuardarDatosUsuarioMouseClicked
        //Guardar los datos
        String nombre, telefono;
        int edad;
        nombre = jTextField1NombreUsuario.getText();
        telefono = jTextField1TelefonoUsuario.getText();
        edad = jSpinner1EdadUsuario.getComponentCount();
        vDatos.add(nombre);
        vDatos.add(telefono);
        
        
        
        //Reiniciar los textos de los campos textField
        jTextField1NombreUsuario.setText("Nombre Usuario");
        jTextField1TelefonoUsuario.setText("Telefono Usuario");
        
        //Avisar al usuario que los datos se han guardados
        JOptionPane.showMessageDialog(this, "Datos " + nombre + " " + telefono + " se ha guardado correctamente");
        
        //Deshabilitar todos los componentes del usuraio
        //Component c[] = jPanel1DatosUsuario.getComponents();
        //    for (Component component : c){
        //    component.setEnabled(false);
            
        //   }
        
        
        //Mostrar datos guardados en el jTextArea
        String texto="";
        for (int i=0;i<vDatos.size();i++) {
            if(vDatos.get(i)!=null && (i==0 || i% 2==0)){
                texto += vDatos.get(i);
            }else{
                 texto += ";" + vDatos.get(i) + "\n";
            }
        }
        jTextArea1AlmacenarDatos.setText("Nombre; Teléfono: " + texto);
    }//GEN-LAST:event_jButton1GuardarDatosUsuarioMouseClicked

    private void jRadioButton1ActivarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1ActivarDatosMouseClicked
       jPanel1DatosUsuario.setEnabled(true);
       jTextArea1AlmacenarDatos.setEnabled(false);
       Component c[] = jPanel1DatosUsuario.getComponents();
        for (Component component : c){
        component.setEnabled(true);
        }   
        
    }//GEN-LAST:event_jRadioButton1ActivarDatosMouseClicked

    private void jRadioButton1ActivarAlmacenamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1ActivarAlmacenamientoMouseClicked
        jPanel1DatosUsuario.setEnabled(false);
       jTextArea1AlmacenarDatos.setEnabled(true);
      Component c[] = jPanel1DatosUsuario.getComponents();
        for (Component component : c){
        component.setEnabled(false);
        }   
    }//GEN-LAST:event_jRadioButton1ActivarAlmacenamientoMouseClicked

    private void jButton1CambiarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1CambiarVentanaMouseClicked
        Ventana2 v = new Ventana2();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1CambiarVentanaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    private ArrayList<String> vDatos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1CambiarVentana;
    private javax.swing.JButton jButton1GuardarDatosUsuario;
    private javax.swing.JButton jButton1Salir;
    private javax.swing.JLabel jLabel1IndicarEdad;
    private javax.swing.JPanel jPanel1DatosUsuario;
    private javax.swing.JRadioButton jRadioButton1ActivarAlmacenamiento;
    private javax.swing.JRadioButton jRadioButton1ActivarDatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1EdadUsuario;
    private javax.swing.JTextArea jTextArea1AlmacenarDatos;
    private javax.swing.JTextField jTextField1NombreUsuario;
    private javax.swing.JTextField jTextField1TelefonoUsuario;
    // End of variables declaration//GEN-END:variables
}
