/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentesgraficosPizza;

import java.util.ArrayList;

/**
 *
 * @author daw-B
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Login = new javax.swing.JPanel();
        jTextField1Usuario = new javax.swing.JTextField();
        jButton1Entrar = new javax.swing.JButton();
        jPasswordField1Contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1Login.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        jTextField1Usuario.setText("Usuario");
        jTextField1Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1UsuarioMouseClicked(evt);
            }
        });

        jButton1Entrar.setText("Entrar");
        jButton1Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1EntrarMouseClicked(evt);
            }
        });

        jPasswordField1Contraseña.setText("Contraseña");
        jPasswordField1Contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1ContraseñaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1LoginLayout = new javax.swing.GroupLayout(jPanel1Login);
        jPanel1Login.setLayout(jPanel1LoginLayout);
        jPanel1LoginLayout.setHorizontalGroup(
            jPanel1LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1LoginLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1Usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButton1Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1Contraseña))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1LoginLayout.setVerticalGroup(
            jPanel1LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1LoginLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jTextField1Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton1Entrar)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jPanel1Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1UsuarioMouseClicked
        jTextField1Usuario.setText("");
    }//GEN-LAST:event_jTextField1UsuarioMouseClicked

    private void jButton1EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1EntrarMouseClicked
        VentanaInicio v = new VentanaInicio();
        v.setVisible(true);
        this.dispose();
        
        String Nombreusuario;
        Nombreusuario = jTextField1Usuario.getText();
        
        usuario = Nombreusuario;
        
    }//GEN-LAST:event_jButton1EntrarMouseClicked

    private void jPasswordField1ContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1ContraseñaMouseClicked
        jPasswordField1Contraseña.setText("");
    }//GEN-LAST:event_jPasswordField1ContraseñaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }
    private String usuario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Entrar;
    private javax.swing.JPanel jPanel1Login;
    private javax.swing.JPasswordField jPasswordField1Contraseña;
    private javax.swing.JTextField jTextField1Usuario;
    // End of variables declaration//GEN-END:variables
}
